### ISSUE TITLE
Is this could be extended to multiphase flows

### ISSUE THREAD

**Issue by chandukec** [IllinoisRocstar/AccelerateCFD_CE#10]
Nice work and thanks for the utility. Not sure if this makes sense or not--- is this utility could be used for multi-phase flows?

**Comment by akashaero** [comment]
Hello,

Currently, we have no plans for extending this software to non-isothermal & multi-phase flows. We have a professional version in development that will support passive and active scalars.

**Comment by chandukec** [comment]
Great, thanks for the reply and update :)
