### ISSUE TITLE
Downloaded and worked on day before version of this utility, need to re-work?

### ISSUE THREAD

**Issue by chandukec** [IllinoisRocstar/AccelerateCFD_CE#11]
Hello, 
Thanks again for this utility. Only yesterday I downloaded, worked on the tutorial case that was already there in the folder and tried to apply on my case. But today saw that the installation method changes ---earlier it was using wmake and that's all, I guess. Now it's cmake--> make install . Is pressure reconstruction added to this? Is this the latest version and I need to re-download and re-install the utility, any suggestions would be a great help. Thanks in advance.

**Comment by akashaero** [comment]
Hello,

Thank you for your interest in this utility. Yes, we have changed the build system from **Wmake** based to **CMake** based to make it compatible with both branches of OpenFOAM software (openfoam.com and openfoam.org). Re-download it and try to build it on your system. Let us know if you have any further questions/difficulties with CMake based system.

Akash

**Comment by chandukec** [comment]
Hi, thanks a lot for your prompt reply, but in addition to the compatibility issue have anything been added or enhanced in this latest version against the previous version?  And could this version be installed while the previous version is still active or the previous version has to be uninstalled ? Thanks again for your help.

**Comment by tjwilso** [comment]
The only thing fixed in the recent patch was a compatibility issue resolved by updating the build system. You should be able to have multiple versions of AccelerateCFD installed at the same time, as long as you are careful to keep the install locations separate.
