### ISSUE TITLE
Unable to install this latest (updgraded) version

### ISSUE THREAD

**Issue by chandukec** [IllinoisRocstar/AccelerateCFD_CE#12]
Hello, 
The previous version of this utility I have installed correctly and was able to re-produce your tutorial graphs etc. But as per our previous conversation: https://github.com/IllinoisRocstar/AccelerateCFD_CE/issues/11#issuecomment-770487809
you have suggested that this version has wide compatibility as against with the previous version. However I would like to point out that I was able to able to run the previous version with the OpenFOAM v1906, but with this newest version of the utility I am not even been able to install it, when I cmake .. then I am getting these errors:
```
-- OpenFOAM link directory /home/xyz/OpenFOAM/OpenFOAM-v1906/platforms/linux64GccDPInt32Opt/lib
-- Could NOT find MPI_C (missing: MPI_mpi_LIBRARY MPI_C_WORKS) 
-- Could NOT find MPI_CXX (missing: MPI_mpi_LIBRARY MPI_CXX_WORKS) 
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindMPI.cmake:1688 (find_package_handle_standard_args)
  CMakeLists.txt:85 (find_package)


-- Configuring incomplete, errors occurred!
```
Also I am using the `cmake version 3.16.3 ` in my new workstation. 

To be noted that I am trying to install this version on another workstation having the same OpenFOAM v1906. Any suggestion or comment will be a great help. Thanks in advance !

**Comment by akashaero** [comment]
I have updated the CMakeLists.txt. Please re-download this repo and try again. 

Thanks!

**Comment by chandukec** [comment]
Hello Akash, 
May thanks for your prompt reply and for quick action, that issue is resolved but still getting the errors while executing `make && make install
`
as: 
```

Install the project...
-- Install configuration: ""
-- Installing: /usr/local/bin/podBasisCalc
CMake Error at cmake_install.cmake:47 (file):
  file INSTALL cannot copy file
  "/home/xyz/OpenFOAM/xyz-v1906/AccelerateCFD_CE-master/build/podBasisCalc"
  to "/usr/local/bin/podBasisCalc": Permission denied.


make: *** [Makefile:85: install] Error 1

```
Is this complaining for super user, meaning, should I run the commands as:
`sudo make `
`sudo make install`
or something else is missing from my side. If suppose I don't have access to the superuser code then in that case, it won't be possible to install this utility ? Sorry for multiple queries and naive doubts. Thanks again for your help.

**Comment by akashaero** [comment]
Hi,

Usually, it should install it into the OpenFOAM bin directory (i.e. /home/xyz/OpenFOAM/OpenFOAM-x.0/platforms/linux64GccDPInt32Opt/bin).

The lines for installation were commented out in CMAKE. I have fixed it. Thanks for pointing this error out. If you would re-download the Cmake file and re-build this, you should be able to install without problems.

**Comment by chandukec** [comment]
Thanks a lot, it worked perfectly.
